### ISSUE TITLE
怎么退出

### ISSUE THREAD

**Issue by pointerbest** [kadds/P2P-Live#1]
https://github.com/kadds/P2P-Live/blob/052be4c0bf7f1b9b4dadc7fe7d9c9a0421a72611/lib/net/tcp.cc#L39

**Comment by kadds** [comment]
wait_client在acceptor协程中运行，等待新的连接。当server 调用close关闭时，结束acceptor协程。
https://github.com/kadds/P2P-Live/blob/052be4c0bf7f1b9b4dadc7fe7d9c9a0421a72611/lib/net/tcp.cc#L81
